# Travis CI Configuration File

services:
  - docker

cache:
  timeout: 1000
  directories:
    - vendor

notifications:
  email: false

before_script:
  - composer install

script:
  - composer test
