# Travis CI Configuration File

services:
  - docker

cache:
  timeout: 1000
  directories:
    - vendor

notifications:
  email: false

before_script:
  - composer install --ignore-platform-reqs

script:
  - composer test -- --coverage-clover=coverage.xml
  - bash <(curl -s https://codecov.io/bash)
