name: Build Release

on:
  release:
    types: [ published ]
  workflow_dispatch:


jobs:
  build-manual-install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      uses: ramsey/composer-install@v1
      with:
        composer-options: '-oa --no-dev'
        php-version: "7.4"

    - name: Archive assets
      uses: thedoctor0/zip-release@master
      with:
        filename: 'manual-install.zip'
        exclusions: '*.git* *tests/ *tests/data/ *tests/* *tests/**/*'
        path: '.'
        directory: '.'

    - name: Upload zip to release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'manual-install.zip'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
